# Uncomment the next line to define a global platform for your project
 platform :ios, '10.3'

pod 'Firebase/Core'
pod 'Firebase/Messaging'

target 'PushTest3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'Alamofire', '~> 4.0'
end