# Uncomment the next line to define a global platform for your project
 platform :ios, '10.3'

pod 'Firebase/Core'
pod 'Firebase/Messaging'

target 'secondTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'Alamofire', '~> 4.0'
   pod 'ObjectMapper', '~> 3.4'
   pod 'AlamofireObjectMapper', '~> 5.2'

end